name: echo_admin_panel_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # utility Packages
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_dropzone: ^4.2.1
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.1.3
  multi_select_flutter: 4.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1



  # Web Specific
  web: ^1.1.1
  http: ^1.3.0
  html: ^0.15.5
  fl_chart: ^0.70.2
  data_table_2: ^2.5.18
  url_strategy: 0.2.0
  
  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # FIrebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.4

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  
   #--------------- LOCAL ASSETS ---------#

  assets:
    - Assets/App_Assets/Icons/
    - Assets/App_Assets/images/Adds/
    - Assets/App_Assets/images/user/
    - Assets/App_Assets/images/Succes_image/
    - Assets/App_Assets/authentication_assets/


  #--------- LOCAL FONTS --------#

  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Fonts/Poppins-Light.ttf
          weight: 300
        - asset: Assets/Fonts/Poppins-Regular.ttf
          weight: 300
        - asset: Assets/Fonts/Poppins-Italic.ttf
          style: italic
        - asset: Assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: Assets/Fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: Assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: Assets/Fonts/Poppins-SemiBoldItalic.ttf
          weight: 800
          style: italic
    - family: coolvetica
      fonts:
        - asset: Assets/Fonts/coolvetica rg.otf
        - asset: Assets/Fonts/coolvetica rg it.otf


