// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL2IZlLliMseQC2yZbtl_pcC3KsoCzv50',
    appId: '1:535446153093:web:1255fbe6f8f386639086ec',
    messagingSenderId: '535446153093',
    projectId: 'echo-review-system',
    authDomain: 'echo-review-system.firebaseapp.com',
    storageBucket: 'echo-review-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtz_NYEuo1pVGILgpdo8FIv7bCM8a97Rc',
    appId: '1:535446153093:android:7a72ac5b6cf7785d9086ec',
    messagingSenderId: '535446153093',
    projectId: 'echo-review-system',
    storageBucket: 'echo-review-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHyQ8M_9y8UAJnEzwtYdqpKh7PD8dgC4Y',
    appId: '1:535446153093:ios:5272a0a089e3dbf59086ec',
    messagingSenderId: '535446153093',
    projectId: 'echo-review-system',
    storageBucket: 'echo-review-system.firebasestorage.app',
    androidClientId: '535446153093-i98mc8ldgk1l7id0155ui7q06k90q600.apps.googleusercontent.com',
    iosClientId: '535446153093-lvfc33jqtq27qk73spqt4jnh0d0mv4f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoAdminPanelFlutter',
  );
}
